server:
  port: 8080
#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purchase?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: UTF-8
      enabled: true
#mybatis xml文件扫描路径
mybatis:
  mapper-locations: classpath*:com/leewm/purchase/dao/**/*.xml
  type-aliases-package: com.leewm.purchase.entity
  
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
   